name: sdcpp
description: "A flutter package for stable diffusion inference"
version: 0.0.0
homepage:

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

ffigen:
  name: 'stable_diffusion'
  description: 'stable-diffusion.cpp binding'
  output: 'lib/src/bindings.dart'
  ignore-source-errors: true
  headers:
    entry-points:
      - 'src/stable_diffusion/stable-diffusion.h'
  compiler-opts:
    - '-I/usr/lib/clang/17/include'

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
