// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// stable-diffusion.cpp binding
class stable_diffusion {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  stable_diffusion(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  stable_diffusion.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int stable_diffusion_init(ffi.Pointer<ffi.Char> params) {
    return _stable_diffusion_init(params);
  }

  late final _stable_diffusion_initPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'stable_diffusion_init',
      );
  late final _stable_diffusion_init =
      _stable_diffusion_initPtr
          .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Pointer<ffi.Char>> stable_diffusion_txt2img(
    ffi.Pointer<ffi.Char> params,
  ) {
    return _stable_diffusion_txt2img(params);
  }

  late final _stable_diffusion_txt2imgPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<ffi.Char>)
    >
  >('stable_diffusion_txt2img');
  late final _stable_diffusion_txt2img =
      _stable_diffusion_txt2imgPtr
          .asFunction<
            ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<ffi.Char>)
          >();

  void stable_diffusion_free() {
    return _stable_diffusion_free();
  }

  late final _stable_diffusion_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('stable_diffusion_free');
  late final _stable_diffusion_free =
      _stable_diffusion_freePtr.asFunction<void Function()>();
}
